project_id = "umbcdnaoeaottdbbpzui"

[functions.generate-exam]
verify_jwt = false

[functions.generate-chapter-quiz]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.explain-slide]
verify_jwt = false

[functions.batch-generate-slides]
verify_jwt = false

[functions.generate-single-slide]
verify_jwt = false
